### PR TITLE
Update ci Ubuntu to 24.04

### PR DESCRIPTION
**Pull request by mcbarton**
This PR updates the Ubuntu used in the ci to the latest version (24.04). The random added line is to check that I didn't break the clang tidy ci by updating to a newer Ubuntu.

### CODE REVIEW

**Comment by mcbarton** [comment]
Converting to draft since although Ubuntu 24.04 are listed as available, the workflow isn't able to get one. At least not on a fast timescale.

**Comment by mcbarton** [comment]
@vgvassilev @alexander-penev Can one of you manually reactivate the workflow? The runners should be available now according to this blog post https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/

**Comment by mcbarton** [comment]
@vgvassilev @alexander-penev can one of you merge this PR now the new runners are available?

**Comment by mcbarton** [comment]
@anutosh491 @JohanMabille can one of you review this PR?

**Review by anutosh491 — APPROVED** [review]
LGTM

**Comment by mcbarton** [comment]
@anutosh491 Thanks for reviewing and approving so fast. Are you able to merge the PR?

**Pull request merged**
