### PR TITLE
Added test cases for xutils and execute_request

### PR DESCRIPTION
**Pull request by UtkarshBhatt6**
This pull request add test cases for xutils and execute_request
### `execute_request`
**`code_execution_failure`**: checks correct error status
**`silent_mode`**: checks payload when no output is expected
**`user_expressions`**: checks correct arithmetic logic
### `xutils`
**`should_print_version_tests`**:The test cases for `should_print_version_tests` verify that the function correctly identifies whether the `--version` argument is provided among the command-line arguments, returning true when present and false otherwise, across various scenarios including its absence, presence among other arguments, and when no or empty arguments are provided.

**`extract_filename_tests`**:The test cases for `extract_filename_tests` validate the correct behavior of the `extract_filename` function in various scenarios, including extracting filenames, handling multiple flag instances, and shifting arguments properly.

**`build_interpreter_tests`**:These test cases for `build_interpreter` ensure that it correctly constructs an interpreter object under different argument configurations, including when provided with correct arguments and when only the process name is provided.

### CODE REVIEW

**Comment by UtkarshBhatt6** [comment]
> @UtkarshBhatt6 your PR is causing the builds on the CI to fail.
> 
> some remarks would be:
> 
> 1. You rely on assigning string constants ( {"program", "--version"}) to a char* which should not be done because this can lead to undefined behavior (generally not a good practice for memory safety reasons)
> 2. There are missing semi-colons, which means you did not run or build this locally
> 
> Please make sure that you rebuild after adding tests, and also run them before pushing your changes

Thanks for your reply Aaron
I am having some issues while i run tests locally
All tests are getting failed
In the build directory ,when when i use make build i am getting these logs
`cmake -D CMAKE_BUILD_TYPE=Release -D CMAKE_PREFIX_PATH=$env:CONDA_PREFIX -D CMAKE_INSTALL_PREFIX=$env:CONDA_PREFIX -D CMAKE_INSTALL_LIBDIR=lib ..`
-- Building for: Visual Studio 17 2022
CMake Deprecation Warning at CMakeLists.txt:9 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is MSVC 19.39.33522.0
-- The CXX compiler identification is MSVC 19.39.33522.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building xeus-cpp v0.3.0
-- Found nlohmann_json: C:/Users/utkar/miniconda3/envs/xeus-cpp/Library/share/cmake/nlohmann_json/nlohmann_jsonConfig.cmake (found suitable version "3.11.2", minimum required is "3.2.0")
-- Found ZLIB: C:/Users/utkar/miniconda3/envs/xeus-cpp/Library/lib/z.lib (found version "1.2.13")
-- Found zstd: C:/Users/utkar/miniconda3/envs/xeus-cpp/Library/lib/zstd.lib
-- Found LibXml2: C:/Users/utkar/miniconda3/envs/xeus-cpp/Library/lib/xml2.lib (found version "2.12.5")
CMake Warning (dev) at C:/Users/utkar/miniconda3/envs/xeus-cpp/Library/lib/cmake/llvm/HandleLLVMOptions.cmake:460 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'LLVM_ENABLE_WARNINGS'.
Call Stack (most recent call first):
  CMakeLists.txt:126 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Using Debug VC++ CRT: MDd
-- Using Release VC++ CRT: MD
-- Using MinSizeRel VC++ CRT: MD
-- Using RelWithDebInfo VC++ CRT: MD
-- Using Release VC++ CRT: MD
CMake Warning (dev) at C:/Users/utkar/miniconda3/envs/xeus-cpp/Library/lib/cmake/llvm/HandleLLVMOptions.cmake:1018 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'LLVM_ENABLE_EH'.
Call Stack (most recent call first):
  CMakeLists.txt:126 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Users/utkar/miniconda3/envs/xeus-cpp/Library/lib/cmake/llvm/HandleLLVMOptions.cmake:1019 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'LLVM_ENABLE_RTTI'.
Call Stack (most recent call first):
  CMakeLists.txt:126 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Users/utkar/miniconda3/envs/xeus-cpp/Library/share/cmake-3.28/Modules/CMakeDependentOption.cmake:75 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'LLVM_EXPORT_SYMBOLS_FOR_PLUGINS'.
Call Stack (most recent call first):
  C:/Users/utkar/miniconda3/envs/xeus-cpp/Library/lib/cmake/llvm/HandleLLVMOptions.cmake:1175 (CMAKE_DEPENDENT_OPTION)
  CMakeLists.txt:126 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for os_signpost_interval_begin
-- Looking for os_signpost_interval_begin - not found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Found OpenSSL: C:/Users/utkar/miniconda3/envs/xeus-cpp/Library/lib/libcrypto.lib (found version "3.2.1")
CMake Deprecation Warning at test/CMakeLists.txt:13 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Configuring done (18.0s)
-- Generating done (0.4s)
-- Build files have been written to: C:/Users/utkar/xeus-cpp/test

can you help me debug these error logs ?

**Comment by anutosh491** [comment]
cc @tharun571 would you be interested in finishing up the work here ? You can continue working on this branch or maybe work on a new branch itself. Would be great if you could finish up the pending work.

**Comment by tharun571** [comment]
@anutosh491 I think all of the tests here have already been written.

**Comment by anutosh491** [comment]
Ohh okay if you can confirm that for me once again that we've covered `xutils` and the `execute_request` (maybe react with a thumbs up on this message) we can close this PR then.

**Comment by tharun571** [comment]
I checked them, they are just variations as they don't cover functions/code that has already been covered. You can close the pr.

**Comment by anutosh491** [comment]
In that case we can close this Pr.

**Pull request closed without merging**
