### PR TITLE
Refactoring build_interpreter function

### PR DESCRIPTION
**Pull request by anutosh491**

### CODE REVIEW

**Comment by anutosh491** [comment]
@vgvassilev I think you started working on introducing clang-tidy. As you're still working on it, should we wait for the CI check to pass before merging anything into master.

**Comment by vgvassilev** [comment]
No, we should not wait for this.

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Comment by anutosh491** [comment]
> No, we should not wait for this. 

Thanks. We could merge it then

**Pull request merged**
