### PR TITLE
Add Jupyter Lite serve instructions to README

### PR DESCRIPTION
**Pull request by mcbarton**
The objective of this PR is to see whether the jupyter serve issue mention here is present in the wasm build in the ci https://github.com/compiler-research/xeus-cpp/issues/61#issuecomment-2124670110

### CODE REVIEW

**Comment by anutosh491** [comment]
Thanks for this. Let's see what the CI says !

**Comment by mcbarton** [comment]
@anutosh491 here is the PR for you to review once you've had a chance to test locally.

**Comment by anutosh491** [comment]
Trying it out now !

**Review by anutosh491 — APPROVED** [review]
Works perfectly. Thanks for this :)
Merging !

**Pull request merged**
